# Generated by Django 5.2.9 on 2025-12-10 04:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(db_index=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stocks',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='StockIngestionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_by', models.CharField(blank=True, max_length=255, null=True)),
                ('request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(choices=[('QUEUED_FOR_FETCH', 'Queued for Fetch'), ('FETCHING', 'Fetching'), ('FETCHED', 'Fetched'), ('QUEUED_FOR_SPARK', 'Queued for Spark'), ('SPARK_RUNNING', 'Spark Running'), ('SPARK_FINISHED', 'Spark Finished'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default='QUEUED_FOR_FETCH', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queued_for_fetch_at', models.DateTimeField(blank=True, null=True)),
                ('fetching_started_at', models.DateTimeField(blank=True, null=True)),
                ('fetching_finished_at', models.DateTimeField(blank=True, null=True)),
                ('queued_for_spark_at', models.DateTimeField(blank=True, null=True)),
                ('spark_started_at', models.DateTimeField(blank=True, null=True)),
                ('spark_finished_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('raw_data_uri', models.CharField(blank=True, max_length=500, null=True)),
                ('processed_data_uri', models.CharField(blank=True, max_length=500, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_runs', to='api.stock')),
            ],
            options={
                'db_table': 'stock_ingestion_runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stock', '-created_at'], name='idx_run_stock_created_at')],
            },
        ),
    ]
