# Generated by Django 5.2.9 on 2025-12-26 18:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkQueueRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_by', models.CharField(blank=True, max_length=255, null=True)),
                ('total_stocks', models.IntegerField(default=0)),
                ('queued_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bulk_queue_runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='idx_bulk_queue_created_at')],
            },
        ),
        migrations.AddField(
            model_name='stockingestionrun',
            name='bulk_queue_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_runs', to='api.bulkqueuerun'),
        ),
    ]
