"""
Django settings for services project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

APP_ENV = os.environ.get("APP_ENV", "dev")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")
if APP_ENV in ["prod", "stage"] and not SECRET_KEY:
    raise ValueError("SECRET_KEY must be set in production environment")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = APP_ENV not in ["prod", "stage"]

CORS_ORIGIN_ALLOW_ALL = False

if APP_ENV in ["dev", "test"]:
    CORS_ALLOWED_ORIGINS = (
        'http://localhost:8081',
        'http://localhost:8080',
        'http://localhost:8000',  # Add the backend itself for same-origin
    )
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:8081',
        'http://localhost:8080',
        'http://localhost:8000',
    ]
    ALLOWED_HOSTS = ["*"]
    CORS_ALLOW_CREDENTIALS = True  # Required for credentials: 'include' in fetch


# Application definition

INSTALLED_APPS = [
    # "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # "django.contrib.sites",  # Required for allauth

    # "drf_spectacular",
    "rest_framework",
    "corsheaders",
    # "rest_framework_simplejwt",

    # Allauth
    # "allauth",
    # "allauth.account",
    # "allauth.headless",  # Headless API for JSON-based authentication

    # Project apps

]

MIDDLEWARE = [
    "config.middleware.health_check_middleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "allauth.account.middleware.AccountMiddleware",  # Required for Allauth
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # Add project-level templates directory
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

SQL_DATABASE = os.environ.get("SQL_DATABASE")
SQL_USER = os.environ.get("username") if APP_ENV in ["stage"] else os.environ.get("SQL_USER")
SQL_PASSWORD = os.environ.get("password") if APP_ENV in ["stage"] else os.environ.get("SQL_PASSWORD")
SQL_HOST = os.environ.get("SQL_HOST")

required_database = {
    "SQL_DATABASE": SQL_DATABASE,
    "SQL_USER": SQL_USER,
    "SQL_PASSWORD": SQL_PASSWORD,
    "SQL_HOST": SQL_HOST,
}

missing = [name for name, val in required_database.items() if not val]
if missing and APP_ENV in ["prod", "stage", "dev"]:
    raise ImproperlyConfigured(
        f"Missing required database settings: {', '.join(missing)}"
    )

if APP_ENV in ["prod", "stage", "dev"]:
    # Production database configuration optimized for RDS
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": SQL_DATABASE,
            "USER": SQL_USER,
            "PASSWORD": SQL_PASSWORD,
            "HOST": SQL_HOST,
            "PORT": "5432",
            "OPTIONS": {
                'connect_timeout': 10,
                # 'application_name': '',
            },
            # Connection pooling settings for RDS with 87 max connections
            'CONN_MAX_AGE': 600,  # 10 minutes - keeps connections alive to reduce overhead
            'CONN_HEALTH_CHECKS': True,  # Verify connections before use
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Cache
REDIS_HOST = os.environ.get("REDIS_HOST")
REDIS_PORT = os.environ.get("REDIS_PORT", "6379")
REDIS_PASSWORD = os.environ.get("REDIS_PASSWORD")
REDIS_DB = os.environ.get("REDIS_DB", "0")

required_redis = {
    "REDIS_HOST": REDIS_HOST,
}

missing = [name for name, val in required_redis.items() if not val]
if missing and APP_ENV in ["prod", "stage", "dev"]:
    raise ImproperlyConfigured(
        f"Missing required Redis settings: {', '.join(missing)}"
    )

if APP_ENV in ["prod", "stage", "dev"]:
    # Build Redis connection URL
    redis_url = f"redis://"
    if REDIS_PASSWORD:
        redis_url += f":{REDIS_PASSWORD}@"
    redis_url += f"{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
    
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': redis_url,
            'TIMEOUT': 300,  # 5 minutes default
            'OPTIONS': {
                'socket_connect_timeout': 5,
                'socket_timeout': 5,
                'retry_on_timeout': True,
                'max_connections': 50,
            }
        }
    }
else:
    # Local file-based cache for testing
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
            'LOCATION': '/tmp/django_cache',
            'TIMEOUT': 300,
            'OPTIONS': {
                'MAX_ENTRIES': 1000,
                'CULL_FREQUENCY': 3,
            }
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Session settings
ACCOUNT_SESSION_REMEMBER = False  # "Remember me" unchecked by default
SESSION_COOKIE_AGE = 43200  # 12 hours (in seconds)
SESSION_SAVE_EVERY_REQUEST = True  # Extend session on activity
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_SECURE = APP_ENV in ["prod", "stage"]
SESSION_COOKIE_HTTPONLY = True
# Lax for development (same-origin), None for production (cross-origin with Secure)
SESSION_COOKIE_SAMESITE = 'None' if APP_ENV in ["prod", "stage"] else 'Lax'

# CSRF Protection
CSRF_USE_SESSIONS = False  # Must be False when using fetch/AJAX - CSRF token needs to be in cookie
CSRF_COOKIE_SECURE = APP_ENV in ["prod", "stage"]
CSRF_COOKIE_HTTPONLY = False  # Must be False to allow JavaScript to read CSRF token
# Lax for development (same-origin), None for production (cross-origin with Secure)
CSRF_COOKIE_SAMESITE = 'None' if APP_ENV in ["prod", "stage"] else 'Lax'

# ============================================
# Email Configuration
# ============================================

# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend" if APP_ENV in ["prod", "stage"] else "django.core.mail.backends.console.EmailBackend"
# DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@localhost')
# SERVER_EMAIL = DEFAULT_FROM_EMAIL

# if APP_ENV in ["stage", "prod"]:
#     # In production, only require email settings
#     EMAIL_HOST = os.environ.get('EMAIL_HOST')
#     EMAIL_PORT = os.environ.get('EMAIL_PORT')
#     EMAIL_USE_TLS = True
#     EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
#     EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')

#     required_email = {
#         "EMAIL_HOST": EMAIL_HOST,
#         "EMAIL_PORT": EMAIL_PORT,
#         "EMAIL_USE_TLS": EMAIL_USE_TLS,
#         "EMAIL_HOST_USER": EMAIL_HOST_USER,
#         "EMAIL_HOST_PASSWORD": EMAIL_HOST_PASSWORD,
#         "DEFAULT_FROM_EMAIL": DEFAULT_FROM_EMAIL,
#     }
#     missing = [name for name, val in required_email.items() if not val]
#     if missing:
#         raise ImproperlyConfigured(
#             f"Missing required email settings: {', '.join(missing)}"
#         )
# ============================================
# AUTHENTICATION CONFIGURATION
# ============================================

# Authentication backends
# AUTHENTICATION_BACKENDS = [
#     'django.contrib.auth.backends.ModelBackend',
#     'allauth.account.auth_backends.AuthenticationBackend',
# ]

# # Custom User Model
# AUTH_USER_MODEL = 'authentication.User'

# # Site Framework (required for allauth)
# SITE_ID = 1

# # Site name and domain for email templates
# SITE_NAME = ""
# SITE_DOMAIN = os.environ.get('SITE_DOMAIN', 'localhost:8000')


# ============================================
# ALLAUTH CONFIGURATION (Updated to new format)
# ============================================

# Authentication method (NEW FORMAT)
# ACCOUNT_LOGIN_METHODS = {'email'}  # Email-only login (no username)
# ACCOUNT_USER_MODEL_USERNAME_FIELD = None  # Disable username completely

# # Email verification
# ACCOUNT_EMAIL_VERIFICATION = 'none'  # Disabled - users don't need email verification
# ACCOUNT_PREVENT_ENUMERATION = True
# ACCOUNT_EMAIL_UNKNOWN_ACCOUNTS = False
# ACCOUNT_EMAIL_NOTIFICATIONS = True
# ACCOUNT_EMAIL_SUBJECT_PREFIX = "[] "
# EMAIL_SUBJECT_PREFIX = "[] "

# # Make headless emails link to your frontend:
# FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:8000')
# HEADLESS_FRONTEND_URLS = {
#     "account_confirm_email": FRONTEND_URL + "/account/verify-email/{key}",
#     "account_reset_password": FRONTEND_URL + "/account/password/reset",
#     "account_reset_password_from_key": FRONTEND_URL + "/account/password/reset/key/{key}",
#     "account_signup": FRONTEND_URL + "/account/signup",
# }

# # PASSWORD RESET FIELDS
# ACCOUNT_PASSWORD_RESET_BY_CODE_TIMEOUT = 1800  # 30 minutes
# # Signup fields (NEW FORMAT)
# # Format: 'field' or 'field*' (asterisk = required)
# ACCOUNT_SIGNUP_FIELDS = [
#     'email*',        # Required: Email address
#     'password1*',    # Required: Password
#     'first_name*',   # Required: First name
#     'last_name*',    # Required: Last name
# ]
# ACCOUNT_UNIQUE_EMAIL = True

# URL redirects
# LOGIN_URL = '/account/login/'
# LOGIN_REDIRECT_URL = '/'  # Dashboard
# ACCOUNT_LOGOUT_REDIRECT_URL = '/account/login/'
# ACCOUNT_SIGNUP_REDIRECT_URL = '/'  # Dashboard

# Password settings
# ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = False

# User activation
# ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = '/'
# ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https' if APP_ENV in ["prod", "stage"] else 'http'

# Custom adapters
# ACCOUNT_ADAPTER = 'authentication.adapters.CustomAccountAdapter'
# HEADLESS_ADAPTER = 'authentication.adapters.CustomHeadlessAdapter'
# ACCOUNT_CHANGE_EMAIL = True

# Custom signup form for additional fields (first_name, last_name)
# This automatically works with both regular and headless signup
# ACCOUNT_SIGNUP_FORM_CLASS = 'authentication.forms.CustomSignupForm'

# ============================================
# ALLAUTH HEADLESS API CONFIGURATION
# ============================================

# Disable traditional allauth views (we use custom views to serve templates)
# HEADLESS_ONLY = True

# Future: Configure these when implementing email confirmation & password reset
# HEADLESS_FRONTEND_URLS = {
#     "account_confirm_email": "http://localhost:8000/account/verify-email/{key}",
#     "account_reset_password_from_key": "http://localhost:8000/account/password/reset/{key}",
# }

# ============================================
# REST FRAMEWORK CONFIGURATION
# ============================================
# Rest Framework Settings
# REST_FRAMEWORK = {
    # 'DEFAULT_AUTHENTICATION_CLASSES': (
    #     'rest_framework.authentication.SessionAuthentication',
    # ),
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated',
    # ),
    # 'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
# }

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
    ),
}

# API Documentation Settings
# SPECTACULAR_SETTINGS = {
#     'TITLE': '',
#     'DESCRIPTION': '',
#     'VERSION': '0.1.0',
#     'SERVE_INCLUDE_SCHEMA': False,
#     # OTHER SETTINGS
# }

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Additional locations of static files
STATICFILES_DIRS = [
    BASE_DIR / "static_project",  # Project-level static files
]

# S3/MinIO Storage Configuration
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME_STATIC = os.environ.get('AWS_STORAGE_BUCKET_NAME_STATIC')
AWS_STORAGE_BUCKET_NAME_MEDIA = os.environ.get('AWS_STORAGE_BUCKET_NAME_MEDIA')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME')
AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL')


STATIC_URL = f'{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME_STATIC}/'
MEDIA_URL = f'{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME_MEDIA}/'


# Use the modern STORAGES configuration for Django 4.2+
if APP_ENV in ["prod", "stage", "dev"]:
    required_s3 = {
        "AWS_STORAGE_BUCKET_NAME_STATIC": AWS_STORAGE_BUCKET_NAME_STATIC,
        "AWS_STORAGE_BUCKET_NAME_MEDIA": AWS_STORAGE_BUCKET_NAME_MEDIA,
        "AWS_S3_REGION_NAME": AWS_S3_REGION_NAME,
        "AWS_S3_ENDPOINT_URL": AWS_S3_ENDPOINT_URL,
    }
    missing = [name for name, val in required_s3.items() if not val]

    if missing:
        raise ImproperlyConfigured(
            f"Missing required S3/MinIO settings: {', '.join(missing)}"
        )

    # Base storage options without credentials
    storage_options = {
        "endpoint_url": AWS_S3_ENDPOINT_URL,
        "access_key": AWS_ACCESS_KEY_ID,
        "secret_key": AWS_SECRET_ACCESS_KEY,
        "bucket_name": AWS_STORAGE_BUCKET_NAME_MEDIA,
        "region_name": AWS_S3_REGION_NAME,
        "file_overwrite": False,
        "object_parameters": {
            'CacheControl': 'max-age=86400',
        },
        "querystring_auth": True,  # Enable signed URLs for media
        "querystring_expire": 3600  # 1 hour,
    }
    
    static_storage_options = {
        "endpoint_url": AWS_S3_ENDPOINT_URL,
        "access_key": AWS_ACCESS_KEY_ID,
        "secret_key": AWS_SECRET_ACCESS_KEY,
        "bucket_name": AWS_STORAGE_BUCKET_NAME_STATIC,
        "region_name": AWS_S3_REGION_NAME,
        "location": "static",
        "file_overwrite": True,
        "querystring_auth": False,  # No signed URLs for static files
    }
    
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": storage_options,
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": static_storage_options,
        },
    }
else:
    # Local storage configuration (testing)
    STATIC_URL = '/static/'
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'json': {
            'format': '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "module": "%(module)s", "message": "%(message)s"}',
            'style': '%',
        },
    },
    'filters': {
        'exclude_health_checks': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda record: not (
                hasattr(record, 'request') and 
                hasattr(record.request, 'path') and
                record.request.path == '/health/'
            ),
        },
        'health_check_only': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda record: (
                hasattr(record, 'request') and 
                hasattr(record.request, 'path') and
                record.request.path == '/health/'
            ),
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'json',  # JSON format for CloudWatch parsing
            'filters': ['exclude_health_checks'],
        },
        'health_checks': {
            'level': 'WARNING',  # Only log health check errors
            'class': 'logging.StreamHandler',
            'formatter': 'json',
            'filters': ['health_check_only'],
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',  # Reduce SQL query logging in production
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'health_checks'],
            'level': 'INFO',
            'propagate': False,
        },
        'allauth': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        "django.security.csrf": {"handlers":["console"], "level":"DEBUG", "propagate": False},
        'authentication': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'config.middleware': {
            'handlers': ['console'],
            'level': 'WARNING',  # Only log warnings and errors from middleware
            'propagate': False,
        },
        'api': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        
        # Reduce noise from third-party libraries
        'boto3': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'botocore': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'urllib3': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# Production-specific settings
if APP_ENV in ["prod", "stage"]:
    # Security Settings
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    X_FRAME_OPTIONS = 'DENY'
    
    # HTTPS Settings - ADD THESE
    SECURE_SSL_REDIRECT = True  # Redirect HTTP to HTTPS
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True

    # CORS and Hosts - ADD THESE
    CORS_ALLOWED_ORIGINS = tuple(
        group.strip() for group in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',') if group.strip()
    )
    ALLOWED_HOSTS = [
        group.strip() for group in os.environ.get('ALLOWED_HOSTS', '').split(',') if group.strip()
    ]

    CORS_ALLOW_CREDENTIALS = True

    # CSRF Trusted Origins - ADD THIS SECTION
    CSRF_TRUSTED_ORIGINS = [
        group.strip() for group in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if group.strip()
    ]
    
    # Performance settings
    DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
    FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
    
    # Disable Django Debug Toolbar and other development tools
    DEBUG_TOOLBAR_CONFIG = {}
    
    # Optimize for production
    TEMPLATE_DEBUG = False
    
    # Security middleware settings
    # SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
